name: Android - Google Play Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  export-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone Repository
      uses: actions/checkout@v4
    
    - name: Load environment variables
      run: |
        cat .env >> $GITHUB_ENV
        echo ".env Loaded."
    
    - name: Install Godot and templates
      run: |
        echo "Downloading Godot: ${GODOT_VERSION}..."
        wget -q https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}/Godot_v${GODOT_VERSION}_linux.x86_64.zip
        wget -q https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}/Godot_v${GODOT_VERSION}_export_templates.tpz
        
        echo "Installing Godot Editor..."
        unzip -q Godot_v${GODOT_VERSION}_linux.x86_64.zip
        sudo mv Godot_v${GODOT_VERSION}_linux.x86_64 /usr/local/bin/godot
        sudo chmod +x /usr/local/bin/godot
        
        # Read the template version directly from the project for perfect synchronization
        TEMPLATE_FOLDER=$(cat android/.build_version | tr -d '\r\n')
        
        echo "Installing Godot Export Templates..."
        mkdir -p ~/.local/share/godot/export_templates/${TEMPLATE_FOLDER}
        unzip -q Godot_v${GODOT_VERSION}_export_templates.tpz
        mv templates/* ~/.local/share/godot/export_templates/${TEMPLATE_FOLDER}/
    
    ## Pre-heating step
    - name: Pre-heat Godot project
      run: |
        godot --headless --editor --quit || true
        echo "Pre-heating complete - .godot/ cache generated"
    
    - name: Export Android Release
      run: |
        godot --headless --export-release "Android - Google Play"
        echo "Export completed"
    
    - name: Upload Release Asset
      uses: actions/upload-artifact@v4
      with:
        name: MonumentValley-release.apk
        path: exports/Android\ -\ Google\ Play/MonumentValley.apk
